sonar.projectKey = attendance_checker_sonar
sonar.projectName = attendance_checker
sonar.projectVersion = 1.0
sonar.sources = src/main
sonar.java.binaries = target/classes
sonar.host.url = http://localhost:9000
# If you add the token in user variable in Edit System Environment you do not need to mention
#sonar.token = <token>
# run with:
#    mvn clean verify sonar:sonar "-Dsonar.projectKey=untitled" "-Dsonar.token=$env:SONAR_TOKEN" "-Dsonar.host.url=http://localhost:9000"